"""Constants for Model Context Protocol (MCP) 2026-07-28 implementation."""

MCP_PROTOCOL_VERSION = "2026-07-28"
SUPPORTED_PROTOCOL_VERSIONS = {MCP_PROTOCOL_VERSION}

# Standard JSON-RPC 2.0 error codes
JSONRPC_PARSE_ERROR = -32700
JSONRPC_INVALID_REQUEST = -32600
JSONRPC_METHOD_NOT_FOUND = -32601
JSONRPC_INVALID_PARAMS = -32602
JSONRPC_INTERNAL_ERROR = -32603

# Application error codes
MCP_UNAUTHORIZED = -32001
MCP_FORBIDDEN = -32003
MCP_RESOURCE_NOT_FOUND = -32004
MCP_RATE_LIMITED = -32029

# Limits
MAX_REQUEST_BODY_BYTES = 256 * 1024  # 256 KB
MAX_TOOL_ARG_STRING_LENGTH = 32 * 1024  # 32 KB
MAX_SEARCH_LIMIT = 50
MAX_RELATED_LIMIT = 20
MAX_CONTEXT_CHARS = 4000

# Server Identity
SERVER_NAME = "memory-passport"
SERVER_VERSION = "1.9.0"
SERVER_INFO = {
    "name": SERVER_NAME,
    "version": SERVER_VERSION,
}

# MCP 2026-07-28 Reserved Metadata Keys
META_SERVER_INFO_KEY = "io.modelcontextprotocol/serverInfo"
META_PROTOCOL_VERSION_KEY = "io.modelcontextprotocol/protocolVersion"
META_CLIENT_INFO_KEY = "io.modelcontextprotocol/clientInfo"
META_CLIENT_CAPABILITIES_KEY = "io.modelcontextprotocol/clientCapabilities"

# Cache hints defaults
DEFAULT_TTL_MS = 0
DEFAULT_CACHE_SCOPE = "private"
